public with sharing class InvokeCloneAPITest {
	/*
	public InvokeCloneAPITest (){
		Clone cc=new Clone();
		string parentObjAPIName=cc.returnAPIObjectName('a0190000001E3JJ');
		Map<string,string> objLabelobjAPI=cc.getAllChildObjNames(parentObjAPIName,'a0190000001E3JJ');
		string clondedParentRecordID=cc.startsClone('a0190000001E3JJ', objLabelobjAPI.values());
		system.debug('clondedParentRecordID:'+clondedParentRecordID);
		system.debug('newParentRecordID:'+cc.newParentRecordID); 
	}
	*/
}